### PR TITLE
added a slightly better readme + added x264 package

### PR DESCRIPTION
**Pull request by steveneighbour**

### CODE REVIEW

**Comment by steveneighbour** [comment]
merging this pull request should trigger a new docker build here - https://hub.docker.com/r/motionproject/motion/builds/

If that works, we are done :)

**Comment by Mr-Dave** [comment]
Looking at this revision as well as the original, there are packages included which are not actually required.  For example, 

`ca-certificates imagemagick curl wget tzdata ffmpeg x264`
Are not technically required for Motion to build or run.  Certs/tz we may want but I'm unclear on the others.

Also, should this target 18.04 instead of 17.10?

**Comment by steveneighbour** [comment]
Docker is a bit special/different than a typical install, in that users cannot install packages themselves without messing about.  We cannot just target what is required to build/run motion, we must also include packages that users will use to interact with the motion daemon once it's built.

ca-certificates - required to perform a git checkout (SSL errors occur otherwise)
imagemagick  - a few people (me included) use this to create montages or manipulate images after motion is detected
curl - required to push images externally (eg slack notifications on movement)
wget  - required to push images externally (eg slack notifications on movement)
tzdata - required so logging within the container and timestamps etc are set to the users timezone
ffmpeg - required if movie_extpipe options are chosen
x264 - required if movie_extpipe options are chosen

We can target whatever you like, i'll bump it to 18.04 and test it locally.

**Comment by steveneighbour** [comment]
18.04 is building now, will let you know if it works.

Just to add on my comments about the packages, adding in mysql support would require some more thought as this will require quite a few extra packages.  Might be smart to have a few variants, which would be git branches linked to dockerhub tags.

eg 
motion:latest = normal build
motion:db = normal build + mysql support

Or we just have one docker build, which is perhaps much larger than it needs to be.  something for later..

**Comment by steveneighbour** [comment]
I've tidied up the readme a bit as well.

Ubuntu 18.04 is now used as the base, dockerhub build will complete soon hopefully.  Feel free to merge if you like or i can make any changes you want next week.

I'll test this at home, will see how it goes stability wise over the weekend.

**Comment by steveneighbour** [comment]
Issue with the build, headless timezone stuff. Will fix it tomorrow.

**Comment by steveneighbour** [comment]
timezone is now fixed up, i'm now using this docker file at home with 6 cameras and it's working well.

I believe this is ready to merge and then seek feedback.

**Pull request merged**
